### ISSUE TITLE
iOS 17 + watchOS 10 roadmap

### ISSUE THREAD

**Issue by basememara** [basememara/PrayKit#21]
## Short term
- [x] Curved watch complication, #5 
- [x] Phone stand by support
- [ ] Watch app redesign
- [ ] Apple Watch Ultra fixes

## Long term
- [ ] Combine widgets; provide options instead
- [ ] Migrate iCloud + UserDefaults to SwiftData

## Bonus
- [ ] Full adhan notifications
- [ ] Better Siri support
- [ ] Mac app + menu bar

**Comment by sarahummyusuf** [comment]
### Widgets Display Issue
Font size is decreased

![incoming-7B768292-5454-4BFF-815D-F9D111EF499C](https://github.com/basememara/PrayKit/assets/117028307/0b67334f-0aa1-43c3-a7ea-7643ae8494a5)
![incoming-1434748C-7D19-45AD-AA31-8CFCFFD12485](https://github.com/basememara/PrayKit/assets/117028307/b4626a6a-33d6-47e9-be7d-c624cb02f058)
![incoming-77C42349-A376-4430-8419-9ABE1A656D75](https://github.com/basememara/PrayKit/assets/117028307/04f3baaa-390e-4a39-992a-0c7b5890e01b)

**Comment by sarahummyusuf** [comment]
### Known Bugs
- [ ] App language does not reflect in widgets or complications
- [ ] Font size decreased in Watch complications 
- [ ] Widget text nearly invisible in Light Mode
- [ ] Countdown minutes changes after second hand passes 6 (30 secs), not 12

### Requests
- [ ] New system default notification sound in iOS 17?
- [ ] Add '+' in front of count up minutes to all widgets for better at a glance view

**Comment by basememara** [comment]
Beta bugs:
- [x] Light mode widget not working
- [x] No background for complication date
- [x] Watch app shrunk its height

**Comment by basememara** [comment]
Dev notes:
- [ ] SwiftData instead of iCloud
- [ ] App Intents architecture for widgets options, Siri, and maybe Vision Pro
- [ ] Drop old SwiftUI stuff like navigation
- [ ] Drop old watch complications architecture

**Comment by basememara** [comment]
Release notes:
- Enhancements for iOS 17 and watchOS 10
- Add StandBy mode support for widgets
- Curved watch complications are back!

**Comment by basememara** [comment]
- [ ] Corner complication cut off on bezels for some devices
- [ ] `MIN` vs `M` truncating
